#include "bsp/bsp_operator_input.h"

#include "ti_msp_dl_config.h"

typedef struct {
    volatile uint8_t events;
    volatile uint32_t high_ticks;
    volatile uint32_t period_ticks;
    volatile bool abs_pwm_ready;
    volatile uint32_t capture_count;
    volatile uint32_t timeout_count;
    volatile uint32_t invalid_count;
#if defined(CAPTURE_ABS_PWM_INST)
    bool capture_synced;
#endif
} operator_input_state_t;

static operator_input_state_t g_operator_input;

void bsp_operator_input_init(void)
{
    g_operator_input.events = 0U;
    g_operator_input.abs_pwm_ready = false;
    g_operator_input.capture_count = 0U;
    g_operator_input.timeout_count = 0U;
    g_operator_input.invalid_count = 0U;
#if defined(GPIO_BUTTONS_START_PIN)
    /* START is wired to PB7 and uses the input pull-up generated by SysConfig. */
    DL_GPIO_setLowerPinsPolarity(GPIO_BUTTONS_PORT, DL_GPIO_PIN_7_EDGE_FALL);
    DL_GPIO_clearInterruptStatus(GPIO_BUTTONS_PORT, GPIO_BUTTONS_START_PIN);
    DL_GPIO_enableInterrupt(GPIO_BUTTONS_PORT, GPIO_BUTTONS_START_PIN);
#endif
#if defined(CAPTURE_ABS_PWM_INST)
    g_operator_input.capture_synced = false;
    /* Allow an open-drain encoder PWM output to idle high during bring-up. */
    DL_GPIO_initPeripheralInputFunctionFeatures(
        GPIO_CAPTURE_ABS_PWM_C0_IOMUX,
        GPIO_CAPTURE_ABS_PWM_C0_IOMUX_FUNC,
        DL_GPIO_INVERSION_DISABLE,
        DL_GPIO_RESISTOR_PULL_UP,
        DL_GPIO_HYSTERESIS_DISABLE,
        DL_GPIO_WAKEUP_DISABLE);
    /* Combined duty/period capture runs in down-counting mode. */
    DL_TimerA_disableInterrupt(CAPTURE_ABS_PWM_INST,
        DL_TIMERA_INTERRUPT_CC1_UP_EVENT);
    DL_TimerA_enableInterrupt(CAPTURE_ABS_PWM_INST,
        DL_TIMERA_INTERRUPT_CC1_DN_EVENT);
    NVIC_ClearPendingIRQ(CAPTURE_ABS_PWM_INST_INT_IRQN);
    NVIC_EnableIRQ(CAPTURE_ABS_PWM_INST_INT_IRQN);
    DL_TimerA_startCounter(CAPTURE_ABS_PWM_INST);
#endif
}

void bsp_operator_input_handle_gpio_interrupt(uint32_t iidx)
{
#if defined(GPIO_BUTTONS_MODE_IIDX)
    if (iidx == (uint32_t) GPIO_BUTTONS_MODE_IIDX) {
        g_operator_input.events |= BSP_OPERATOR_EVENT_MODE;
    }
#endif
#if defined(GPIO_BUTTONS_START_IIDX)
    if (iidx == (uint32_t) GPIO_BUTTONS_START_IIDX) {
        g_operator_input.events |= BSP_OPERATOR_EVENT_START;
    }
#elif defined(GPIO_BUTTONS_START_PIN)
    if (iidx == (uint32_t) DL_GPIO_IIDX_DIO7) {
        g_operator_input.events |= BSP_OPERATOR_EVENT_START;
    }
#endif
}

void bsp_operator_input_capture_irq_handler(void)
{
#if defined(CAPTURE_ABS_PWM_INST)
    switch (DL_TimerA_getPendingInterrupt(CAPTURE_ABS_PWM_INST)) {
        case DL_TIMERA_IIDX_CC1_DN:
            g_operator_input.capture_count++;
            if (g_operator_input.capture_synced) {
                uint32_t load_ticks = DL_TimerA_getLoadValue(CAPTURE_ABS_PWM_INST);
                uint32_t captured_period_ticks = DL_TimerA_getCaptureCompareValue(
                    CAPTURE_ABS_PWM_INST, DL_TIMER_CC_1_INDEX);
                uint32_t captured_high_ticks = DL_TimerA_getCaptureCompareValue(
                    CAPTURE_ABS_PWM_INST, DL_TIMER_CC_0_INDEX);
                uint32_t period_ticks = load_ticks - captured_period_ticks;
                uint32_t high_ticks = load_ticks - captured_high_ticks;
                if ((period_ticks != 0U) && (high_ticks <= period_ticks)) {
                    g_operator_input.high_ticks = high_ticks;
                    g_operator_input.period_ticks = period_ticks;
                    g_operator_input.abs_pwm_ready = true;
                } else {
                    g_operator_input.invalid_count++;
                }
            } else {
                /* The first edge after a timeout only re-establishes capture sync. */
                g_operator_input.capture_synced = true;
            }
            /* TIMER_ERR_01 requires a manual reload after each completed frame. */
            DL_TimerA_setTimerCount(CAPTURE_ABS_PWM_INST,
                DL_TimerA_getLoadValue(CAPTURE_ABS_PWM_INST));
            break;
        case DL_TIMERA_IIDX_ZERO:
            g_operator_input.capture_synced = false;
            g_operator_input.timeout_count++;
            break;
        default:
            break;
    }
#endif
}

uint8_t bsp_operator_input_take_events(void)
{
    uint8_t events;

    __disable_irq();
    events = g_operator_input.events;
    g_operator_input.events = 0U;
    __enable_irq();
    return events;
}

bool bsp_operator_input_take_abs_pwm(uint32_t *high_ticks, uint32_t *period_ticks)
{
    bool ready;

    if ((high_ticks == NULL) || (period_ticks == NULL)) {
        return false;
    }
    __disable_irq();
    ready = g_operator_input.abs_pwm_ready;
    if (ready) {
        *high_ticks = g_operator_input.high_ticks;
        *period_ticks = g_operator_input.period_ticks;
        g_operator_input.abs_pwm_ready = false;
    }
    __enable_irq();
    return ready;
}

void bsp_operator_input_get_abs_pwm_diagnostics(uint32_t *capture_count,
    uint32_t *timeout_count, uint32_t *invalid_count)
{
    if ((capture_count == NULL) || (timeout_count == NULL) ||
        (invalid_count == NULL)) {
        return;
    }

    __disable_irq();
    *capture_count = g_operator_input.capture_count;
    *timeout_count = g_operator_input.timeout_count;
    *invalid_count = g_operator_input.invalid_count;
    __enable_irq();
}
